import {
  formatAuc,
  formatMoney,
  formatPct,
  getMeta,
  getOnboarding,
  getProjectedStatement,
  getReconciliation,
  getRetrain,
} from './demo-data.js';

/**
 * Shadow-mode dashboard (demo). Every number is generated by the Phase-1 world model
 * (see @ax10m/backtest), so nothing here can contradict the backtest. Two honest
 * stories: (1) the PROJECTED recoverable opportunity in shadow mode (holdoutVerified:
 * false), and (2) an active-holdout signed statement that — because the engine does not
 * yet beat Smart Retries — honestly bills $0, and which anyone can verify.
 */
export default function Page() {
  const statement = getProjectedStatement();
  const r = statement.result;
  const currency = statement.currency;
  const { export: recon, recon: tie } = getReconciliation();
  const onb = getOnboarding();
  const rt = getRetrain();
  const meta = getMeta();
  const day = Math.floor(onb.progress.elapsedDays);

  return (
    <main className="container">
      <div className="onboard" style={{ borderColor: '#f59e0b' }}>
        <div className="onboard-top">
          <span className="badge" style={{ background: '#7c2d12' }}>
            Demo · synthetic data · reproduces the Phase-1 backtest
          </span>
          <a className="activate" href="https://github.com/mkallberg21/AX10M/blob/main/packages/backtest/out/report.md" style={{ textDecoration: 'none' }}>
            Read the backtest →
          </a>
        </div>
        <p className="onboard-note" style={{ marginTop: 12 }}>
          <strong>Honest status:</strong> the AX10M engine now <strong>beats Stripe Smart Retries on recovery
          rate</strong> (+~13.8&nbsp;pp vs the default reach) via a capability a blanket retry can&apos;t copy —{' '}
          <strong>dead-credential recovery</strong> (Account Updater, backup-rail fallback, dunning) recovers cards a
          retry on the original number never reaches. The win <strong>survives the fairness sweep</strong> (it holds
          against a baseline that retries just as long). But this is a <strong>modeled</strong> result on synthetic
          data — the magnitude is assumption-driven, and a <strong>live holdout is what proves it</strong>. Both cards
          come from the same world model, so this demo cannot show a number the backtest denies.
        </p>
      </div>

      <div className="onboard">
        <div className="onboard-top">
          <span className="badge">
            Shadow mode · day {day} of {onb.state.shadowWindowDays} · measuring your true baseline
          </span>
          <button className="activate" disabled title="Demo — activation is disabled">
            Activate at day {onb.state.shadowWindowDays}
          </button>
        </div>
        <div className="progress" role="progressbar" aria-valuenow={Math.round(onb.progress.pctComplete * 100)}>
          <div className="fill" style={{ width: `${Math.round(onb.progress.pctComplete * 100)}%` }} />
        </div>
        <div className="onboard-stats">
          <div><span className="k">Projected monthly opportunity</span><span className="v accent">{formatMoney(onb.projection.projectedMonthlyValue.amount)}</span></div>
          <div><span className="k">Would-be fee (12%)</span><span className="v">{formatMoney(onb.projection.projectedMonthlyFee.amount)}</span></div>
          <div><span className="k">Conservative low end</span><span className="v">{formatMoney(onb.projection.projectedMonthlyConservative.amount)}</span></div>
          <div><span className="k">Your baseline recovery</span><span className="v">{formatPct(onb.projection.baselineRecoveryRate)}</span></div>
        </div>
        <p className="onboard-note">
          Projected from {onb.projection.observedFailures.toLocaleString()} observed baseline failures — a model
          estimate of the recoverable <strong>opportunity</strong>, <strong>not yet holdout-verified</strong> and
          not a claim that our engine captures it. The live holdout is what turns this into a billable number.
        </p>
      </div>

      <h1>Active-holdout statement (illustrative)</h1>
      <p className="subtitle">
        What an active month looks like: a live randomized holdout runs the AX10M engine against your Stripe
        Smart Retries baseline, and we bill only the <strong>always-valid lower bound</strong>. In this (simulated)
        month the engine recovered <strong>{formatPct(r.treatmentRate)}</strong> vs the baseline&apos;s{' '}
        <strong>{formatPct(r.controlRate)}</strong> — a <strong>{formatPct(r.rateDiff)}</strong> difference, driven by
        dead-credential recovery — so the lower bound is positive and it would bill{' '}
        <strong>{formatMoney(r.fee.amount, currency)}</strong>. On a real merchant the same machinery bills{' '}
        <strong>$0</strong> until the lower bound clears; here it clears because the modeled lift is real (and still
        needs a live holdout to prove the size).
      </p>

      <section className="kpis">
        <div className="kpi">
          <div className="label">Proven incremental uplift (lower bound)</div>
          <div className="value accent">{formatMoney(r.lowerDollarsCum.amount, currency)}</div>
          <div className="hint">
            Point estimate {formatMoney(Math.round(r.deltaPer * r.treatedInvoices), currency)}/period · we bill only the proven floor
          </div>
        </div>
        <div className="kpi">
          <div className="label">Fee (12% of proven increment)</div>
          <div className="value">{formatMoney(r.fee.amount, currency)}</div>
          <div className="hint">{r.billable ? 'On truly-incremental dollars' : 'Not billable — lift unproven'}</div>
        </div>
        <div className="kpi">
          <div className="label">Statistical status</div>
          <div className="value">
            {r.billable ? 'Proven' : 'Unproven'}
            <span style={{ color: 'var(--muted)', fontSize: 18 }}> · 95% CS</span>
          </div>
          <div className="hint">
            SRM χ²={r.srm.chiSquare.toFixed(1)} {r.srm.breached ? '✗ paused' : '✓ balanced'} · CUPED −
            {formatPct(r.cupedVarianceReduction)} variance
          </div>
        </div>
      </section>

      <div className="method-strip">
        <span><strong>{formatMoney(Math.round(r.deltaPer), currency)}</strong>/invoice point estimate</span>
        <span><strong>{formatMoney(Math.round(r.halfWidth), currency)}</strong> mSPRT half-width</span>
        <span><strong>{formatMoney(Math.round(r.lowerPer), currency)}</strong>/invoice proven floor</span>
        <span><strong>{formatMoney(Math.round(r.se), currency)}</strong> cluster-robust SE</span>
        <span><strong>{Math.round(r.effectiveN).toLocaleString()}</strong> effective N</span>
      </div>

      <div className="section-title">Cohort breakdown (by MRR tier · decline family · issuer region)</div>
      <table>
        <thead>
          <tr>
            <th>Cohort</th>
            <th className="num">Control recovery</th>
            <th className="num">Treatment recovery</th>
            <th className="num">Point uplift $/inv</th>
            <th className="num">Treated invoices</th>
            <th className="num">Weight</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {r.perStratum.map((line) => (
            <tr key={line.stratumKey}>
              <td>{line.stratumKey === '__pooled__' ? 'pooled (sub-floor)' : line.stratumKey}</td>
              <td className="num">{formatPct(line.controlRate)}</td>
              <td className="num">{formatPct(line.treatmentRate)}</td>
              <td className="num">{formatMoney(Math.round(line.deltaPerStratum), currency)}</td>
              <td className="num">{line.treatmentInvoices.toLocaleString()}</td>
              <td className="num">{formatPct(line.weight)}</td>
              <td>{line.pooled ? <span className="pill holdout">Pooled</span> : <span className="pill billable">In sample</span>}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="subtitle" style={{ fontSize: 13, marginTop: 12 }}>
        The gap concentrates in the <strong>dead-credential</strong> cohorts (expired / lost / stolen / closed cards),
        where the engine&apos;s Account Updater + backup-rail + dunning recover invoices a retry on the original card
        cannot. On the soft-decline majority the two are close. The estimator reports the difference faithfully; a live
        holdout is what proves the magnitude.
      </p>

      <div className="section-title">CFO reconciliation — verify it yourself, trust nothing</div>
      <div className="method-strip">
        <span>Signed statement <strong>{recon.statementHash.slice(0, 16)}…</strong></span>
        <span>Signing key <strong>{recon.signingKeyId}</strong></span>
        <span>Ledger <strong>{recon.ledgerVerified ? 'verified ✓' : 'FAILED ✗'}</strong></span>
        <span>Epoch salt <strong>disclosed</strong></span>
      </div>
      <div className="recon-grid">
        <div className={`recon-card${tie.tiesOut ? ' ok' : ''}`}>
          <div className="label">Reconciles against processor payout</div>
          <div className="big">{tie.tiesOut ? 'Ties out ✓' : 'Discrepancy ✗'}</div>
          <div className="hint">
            {tie.matched.toLocaleString()} recovered txns · {formatMoney(tie.oursTotal, currency)} ={' '}
            {formatMoney(tie.theirsTotal, currency)} settled
          </div>
        </div>
        <div className="recon-card">
          <div className="label">Recovered value (both arms)</div>
          <div className="big">{formatMoney(recon.summary.treatment.recoveredAmount + recon.summary.control.recoveredAmount, currency)}</div>
          <div className="hint">
            Treatment {formatMoney(recon.summary.treatment.recoveredAmount, currency)} · control{' '}
            {formatMoney(recon.summary.control.recoveredAmount, currency)}
          </div>
        </div>
        <div className="recon-card">
          <div className="label">Fee = 12% × proven increment</div>
          <div className="big">{formatMoney(recon.fee.fee, currency)}</div>
          <div className="hint">{recon.fee.billable ? 'proven' : 'unproven → $0'} · recomputable by hand</div>
        </div>
      </div>

      <div className="section-title">Recovery model — retrained off the ledger (the flywheel)</div>
      <p className="subtitle" style={{ marginTop: 0 }}>
        Every recovery decision and its realized outcome are logged to the shared, hash-chained ledger. The retrain
        job reads that ledger, fits a challenger, and a <strong>champion/challenger gate</strong> promotes it only if
        it beats the current model by a margin — so retraining can <strong>never ship a regression</strong>. The gate
        below is production code; the corpus here is synthetic until a live ledger fills.
      </p>
      <section className="kpis">
        <div className="kpi">
          <div className="label">Trained champion (held-out AUC)</div>
          <div className="value accent">{formatAuc(rt.championAuc)}</div>
          <div className="hint">vs an untrained cold-start model at {formatAuc(rt.coldStartAuc)}</div>
        </div>
        <div className="kpi">
          <div className="label">Retrained challenger</div>
          <div className="value">
            {formatAuc(rt.challengerAuc)}
            <span style={{ color: 'var(--muted)', fontSize: 18 }}> AUC</span>
          </div>
          <div className="hint">
            {rt.promotedVsColdStart ? 'Promotes vs cold-start ✓' : 'Held vs cold-start'} ·{' '}
            {rt.promotedVsChampion ? 'promotes vs champion ✓' : 'held vs champion (no gain ≥ margin)'}
          </div>
        </div>
        <div className="kpi">
          <div className="label">Gate decision this cycle</div>
          <div className="value">{rt.promotedVsChampion ? 'Promote' : 'Hold'}</div>
          <div className="hint">
            needs +{rt.marginAuc.toFixed(3)} AUC to promote · never ships a regression
          </div>
        </div>
      </section>
      <div className="method-strip">
        <span><strong>{rt.corpusSamples.toLocaleString()}</strong> labeled ledger samples</span>
        <span><strong>{rt.positives.toLocaleString()}</strong> recovered (+)</span>
        <span><strong>{rt.negatives.toLocaleString()}</strong> failed (−)</span>
        <span>promotes a real gain → <strong>model.promoted</strong> in the ledger</span>
        <span>API + worker load the active champion at startup</span>
      </div>
      <p className="subtitle" style={{ fontSize: 13, marginTop: 12 }}>
        Here the fresh challenger ({formatAuc(rt.challengerAuc)}) does <strong>not</strong> beat the already-strong
        shipped champion ({formatAuc(rt.championAuc)}) by the margin, so the gate correctly <strong>holds</strong> —
        it would promote against a weaker model (as shown vs cold-start), but it refuses to ship a non-improvement.
        That safety property is the point: the flywheel only ever moves the model forward.
      </p>

      <div className="onboard" style={{ marginTop: 20 }}>
        <div className="onboard-top"><span className="badge">Download &amp; verify the signed statement</span></div>
        <p className="onboard-note" style={{ marginTop: 12 }}>
          The Ed25519-signed statement, the reconciliation CSV, the hash-chained ledger, and the public key are
          downloadable so a skeptical CFO can recompute and verify everything without trusting this dashboard:
        </p>
        <ul style={{ margin: '8px 0 12px 18px', lineHeight: 1.9 }}>
          <li><a href="/uplift-statement.json">uplift-statement.json</a> — the signed statement</li>
          <li><a href="/uplift-statement.csv">uplift-statement.csv</a> — recovered transactions (tie to your Stripe payout)</li>
          <li><a href="/uplift-ledger.json">uplift-ledger.json</a> — the hash-chained ledger</li>
          <li><a href="/ax10m-demo-pubkey.pem">ax10m-demo-pubkey.pem</a> — the public key</li>
        </ul>
        <pre style={{ background: '#0b1220', color: '#cbd5e1', padding: 12, borderRadius: 8, overflowX: 'auto', fontSize: 12 }}>
{`node scripts/verify-statement.mjs \\
  uplift-statement.json ax10m-demo-pubkey.pem uplift-ledger.json
# → PASS statement hash · PASS Ed25519 signature · PASS ledger chain`}
        </pre>
      </div>

      <p className="ledger-note">
        {meta.note} · notarized against ledger head {statement.ledgerHead.slice(0, 24)}… · integrity{' '}
        {statement.ledgerVerified ? 'verified ✓' : 'FAILED ✗'} · statement signed {recon.signingKeyId}
      </p>
    </main>
  );
}
