import {
  formatMoney,
  formatPct,
  getMeta,
  getOnboarding,
  getProjectedStatement,
  getReconciliation,
} from './demo-data.js';

/**
 * Shadow-mode dashboard (demo). Every number is generated by the Phase-1 world model
 * (see @ax10m/backtest), so nothing here can contradict the backtest. Two honest
 * stories: (1) the PROJECTED recoverable opportunity in shadow mode (holdoutVerified:
 * false), and (2) an active-holdout signed statement that — because the engine does not
 * yet beat Smart Retries — honestly bills $0, and which anyone can verify.
 */
export default function Page() {
  const statement = getProjectedStatement();
  const r = statement.result;
  const currency = statement.currency;
  const { export: recon, recon: tie } = getReconciliation();
  const onb = getOnboarding();
  const meta = getMeta();
  const day = Math.floor(onb.progress.elapsedDays);

  return (
    <main className="container">
      <div className="onboard" style={{ borderColor: '#f59e0b' }}>
        <div className="onboard-top">
          <span className="badge" style={{ background: '#7c2d12' }}>
            Demo · synthetic data · reproduces the Phase-1 backtest
          </span>
          <a className="activate" href="https://github.com/mkallberg21/AX10M/blob/main/packages/backtest/out/report.md" style={{ textDecoration: 'none' }}>
            Read the backtest →
          </a>
        </div>
        <p className="onboard-note" style={{ marginTop: 12 }}>
          <strong>Honest status:</strong> in the first backtest the AX10M engine <strong>does not beat Stripe
          Smart Retries</strong> — it underperforms by ~19 pp on recovery rate (front-loaded retry timing).
          So the signed statement below correctly bills <strong>$0</strong>. The top card is the <em>projected
          opportunity</em> we&apos;d measure in shadow mode — a model estimate, <strong>not holdout-verified</strong>.
          Both are generated from the same world model, so this demo cannot show a number the backtest denies.
        </p>
      </div>

      <div className="onboard">
        <div className="onboard-top">
          <span className="badge">
            Shadow mode · day {day} of {onb.state.shadowWindowDays} · measuring your true baseline
          </span>
          <button className="activate" disabled title="Demo — activation is disabled">
            Activate at day {onb.state.shadowWindowDays}
          </button>
        </div>
        <div className="progress" role="progressbar" aria-valuenow={Math.round(onb.progress.pctComplete * 100)}>
          <div className="fill" style={{ width: `${Math.round(onb.progress.pctComplete * 100)}%` }} />
        </div>
        <div className="onboard-stats">
          <div><span className="k">Projected monthly opportunity</span><span className="v accent">{formatMoney(onb.projection.projectedMonthlyValue.amount)}</span></div>
          <div><span className="k">Would-be fee (12%)</span><span className="v">{formatMoney(onb.projection.projectedMonthlyFee.amount)}</span></div>
          <div><span className="k">Conservative low end</span><span className="v">{formatMoney(onb.projection.projectedMonthlyConservative.amount)}</span></div>
          <div><span className="k">Your baseline recovery</span><span className="v">{formatPct(onb.projection.baselineRecoveryRate)}</span></div>
        </div>
        <p className="onboard-note">
          Projected from {onb.projection.observedFailures.toLocaleString()} observed baseline failures — a model
          estimate of the recoverable <strong>opportunity</strong>, <strong>not yet holdout-verified</strong> and
          not a claim that our engine captures it. The live holdout is what turns this into a billable number.
        </p>
      </div>

      <h1>Active-holdout statement (illustrative)</h1>
      <p className="subtitle">
        What an active month looks like: a live randomized holdout runs the AX10M engine against your Stripe
        Smart Retries baseline, and we bill only the <strong>always-valid lower bound</strong>. In this demo the
        engine recovered <strong>{formatPct(r.treatmentRate)}</strong> vs the baseline&apos;s{' '}
        <strong>{formatPct(r.controlRate)}</strong> — a <strong>{formatPct(r.rateDiff)}</strong> difference — so the
        proven lift is not positive and the fee is <strong>$0</strong>. That is the product working as designed:
        an unproven month bills nothing.
      </p>

      <section className="kpis">
        <div className="kpi">
          <div className="label">Proven incremental uplift (lower bound)</div>
          <div className="value accent">{formatMoney(r.lowerDollarsCum.amount, currency)}</div>
          <div className="hint">
            Point estimate {formatMoney(Math.round(r.deltaPer * r.treatedInvoices), currency)}/period · we bill only the proven floor
          </div>
        </div>
        <div className="kpi">
          <div className="label">Fee (12% of proven increment)</div>
          <div className="value">{formatMoney(r.fee.amount, currency)}</div>
          <div className="hint">{r.billable ? 'On truly-incremental dollars' : 'Not billable — lift unproven'}</div>
        </div>
        <div className="kpi">
          <div className="label">Statistical status</div>
          <div className="value">
            {r.billable ? 'Proven' : 'Unproven'}
            <span style={{ color: 'var(--muted)', fontSize: 18 }}> · 95% CS</span>
          </div>
          <div className="hint">
            SRM χ²={r.srm.chiSquare.toFixed(1)} {r.srm.breached ? '✗ paused' : '✓ balanced'} · CUPED −
            {formatPct(r.cupedVarianceReduction)} variance
          </div>
        </div>
      </section>

      <div className="method-strip">
        <span><strong>{formatMoney(Math.round(r.deltaPer), currency)}</strong>/invoice point estimate</span>
        <span><strong>{formatMoney(Math.round(r.halfWidth), currency)}</strong> mSPRT half-width</span>
        <span><strong>{formatMoney(Math.round(r.lowerPer), currency)}</strong>/invoice proven floor</span>
        <span><strong>{formatMoney(Math.round(r.se), currency)}</strong> cluster-robust SE</span>
        <span><strong>{Math.round(r.effectiveN).toLocaleString()}</strong> effective N</span>
      </div>

      <div className="section-title">Cohort breakdown (by MRR tier · decline family · issuer region)</div>
      <table>
        <thead>
          <tr>
            <th>Cohort</th>
            <th className="num">Control recovery</th>
            <th className="num">Treatment recovery</th>
            <th className="num">Point uplift $/inv</th>
            <th className="num">Treated invoices</th>
            <th className="num">Weight</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {r.perStratum.map((line) => (
            <tr key={line.stratumKey}>
              <td>{line.stratumKey === '__pooled__' ? 'pooled (sub-floor)' : line.stratumKey}</td>
              <td className="num">{formatPct(line.controlRate)}</td>
              <td className="num">{formatPct(line.treatmentRate)}</td>
              <td className="num">{formatMoney(Math.round(line.deltaPerStratum), currency)}</td>
              <td className="num">{line.treatmentInvoices.toLocaleString()}</td>
              <td className="num">{formatPct(line.weight)}</td>
              <td>{line.pooled ? <span className="pill holdout">Pooled</span> : <span className="pill billable">In sample</span>}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="subtitle" style={{ fontSize: 13, marginTop: 12 }}>
        Treatment recovery is <strong>below</strong> control in most cohorts here — the engine&apos;s retry cadence
        is too front-loaded for this world&apos;s recovery timing (see the backtest). The estimator reports that
        faithfully rather than papering over it.
      </p>

      <div className="section-title">CFO reconciliation — verify it yourself, trust nothing</div>
      <div className="method-strip">
        <span>Signed statement <strong>{recon.statementHash.slice(0, 16)}…</strong></span>
        <span>Signing key <strong>{recon.signingKeyId}</strong></span>
        <span>Ledger <strong>{recon.ledgerVerified ? 'verified ✓' : 'FAILED ✗'}</strong></span>
        <span>Epoch salt <strong>disclosed</strong></span>
      </div>
      <div className="recon-grid">
        <div className={`recon-card${tie.tiesOut ? ' ok' : ''}`}>
          <div className="label">Reconciles against processor payout</div>
          <div className="big">{tie.tiesOut ? 'Ties out ✓' : 'Discrepancy ✗'}</div>
          <div className="hint">
            {tie.matched.toLocaleString()} recovered txns · {formatMoney(tie.oursTotal, currency)} ={' '}
            {formatMoney(tie.theirsTotal, currency)} settled
          </div>
        </div>
        <div className="recon-card">
          <div className="label">Recovered value (both arms)</div>
          <div className="big">{formatMoney(recon.summary.treatment.recoveredAmount + recon.summary.control.recoveredAmount, currency)}</div>
          <div className="hint">
            Treatment {formatMoney(recon.summary.treatment.recoveredAmount, currency)} · control{' '}
            {formatMoney(recon.summary.control.recoveredAmount, currency)}
          </div>
        </div>
        <div className="recon-card">
          <div className="label">Fee = 12% × proven increment</div>
          <div className="big">{formatMoney(recon.fee.fee, currency)}</div>
          <div className="hint">{recon.fee.billable ? 'proven' : 'unproven → $0'} · recomputable by hand</div>
        </div>
      </div>

      <div className="onboard" style={{ marginTop: 20 }}>
        <div className="onboard-top"><span className="badge">Download &amp; verify the signed statement</span></div>
        <p className="onboard-note" style={{ marginTop: 12 }}>
          The Ed25519-signed statement, the reconciliation CSV, the hash-chained ledger, and the public key are
          downloadable so a skeptical CFO can recompute and verify everything without trusting this dashboard:
        </p>
        <ul style={{ margin: '8px 0 12px 18px', lineHeight: 1.9 }}>
          <li><a href="/uplift-statement.json">uplift-statement.json</a> — the signed statement</li>
          <li><a href="/uplift-statement.csv">uplift-statement.csv</a> — recovered transactions (tie to your Stripe payout)</li>
          <li><a href="/uplift-ledger.json">uplift-ledger.json</a> — the hash-chained ledger</li>
          <li><a href="/ax10m-demo-pubkey.pem">ax10m-demo-pubkey.pem</a> — the public key</li>
        </ul>
        <pre style={{ background: '#0b1220', color: '#cbd5e1', padding: 12, borderRadius: 8, overflowX: 'auto', fontSize: 12 }}>
{`node scripts/verify-statement.mjs \\
  uplift-statement.json ax10m-demo-pubkey.pem uplift-ledger.json
# → PASS statement hash · PASS Ed25519 signature · PASS ledger chain`}
        </pre>
      </div>

      <p className="ledger-note">
        {meta.note} · notarized against ledger head {statement.ledgerHead.slice(0, 24)}… · integrity{' '}
        {statement.ledgerVerified ? 'verified ✓' : 'FAILED ✗'} · statement signed {recon.signingKeyId}
      </p>
    </main>
  );
}
