import type { Metadata } from 'next';

/**
 * /schedule — the "see AX10M in action" hub the pitch page's CTA points at. Two paths:
 * explore the live demo yourself, or book a guided walkthrough. The booking link is
 * config-driven (NEXT_PUBLIC_SCHEDULER_URL, e.g. a Calendly URL); until it's set the
 * button is disabled with a clear hint, so a deploy is never broken or misleading.
 */
export const metadata: Metadata = {
  title: 'See AX10M in action',
  description: 'Explore the live demo or book a guided walkthrough of AX10M failed-payment recovery.',
};

const SCHEDULER_URL = process.env.NEXT_PUBLIC_SCHEDULER_URL;

export default function SchedulePage() {
  return (
    <main className="container">
      <div className="onboard-top" style={{ marginBottom: 24 }}>
        <span className="badge">Live demo</span>
        <a className="activate" href="/pitch.html" style={{ textDecoration: 'none', background: 'var(--panel-2)', color: 'var(--text)', border: '1px solid var(--border)' }}>
          ← Back to the pitch
        </a>
      </div>

      <h1>See AX10M in action</h1>
      <p className="subtitle">
        AX10M recovers failed subscription payments and bills only a live-holdout-verified lower bound — so an
        unproven month bills <strong>$0</strong>. Explore the demo yourself, or book a walkthrough and we&apos;ll run
        it against your own decline mix.
      </p>

      <section className="kpis">
        <div className="kpi">
          <div className="label">Explore it yourself</div>
          <div className="value" style={{ fontSize: 22 }}>Live demo</div>
          <div className="hint" style={{ marginBottom: 14 }}>
            Projected opportunity, an honest $0-billed holdout statement, CFO-reconcilable signed ledger, and the
            champion/challenger retrain gate — all from the Phase-1 world model.
          </div>
          <a className="activate" href="/" style={{ textDecoration: 'none', display: 'inline-block' }}>
            Open the live demo →
          </a>
        </div>

        <div className="kpi">
          <div className="label">Book a guided walkthrough</div>
          <div className="value" style={{ fontSize: 22 }}>30 minutes</div>
          <div className="hint" style={{ marginBottom: 14 }}>
            We connect in shadow mode (read-only), measure your true baseline, and show the projected uplift and
            would-be fee before you activate anything. No credentials needed to start.
          </div>
          {SCHEDULER_URL ? (
            <a className="activate" href={SCHEDULER_URL} target="_blank" rel="noopener" style={{ textDecoration: 'none', display: 'inline-block' }}>
              Pick a time →
            </a>
          ) : (
            <>
              <button className="activate" disabled>Booking link coming soon</button>
              <div className="hint" style={{ marginTop: 8 }}>
                Set <code>NEXT_PUBLIC_SCHEDULER_URL</code> (e.g. a Calendly link) to enable this button.
              </div>
            </>
          )}
        </div>
      </section>

      <div className="section-title">What you&apos;ll see</div>
      <div className="method-strip">
        <span><strong>Shadow onboarding</strong> — measure your baseline, no money moves</span>
        <span><strong>Signed statement</strong> — Ed25519, reconcilable to your payout</span>
        <span><strong>Bill the lower bound</strong> — unproven → $0</span>
        <span><strong>The flywheel</strong> — retrain gate that never ships a regression</span>
      </div>

      <p className="ledger-note">
        The demo runs on synthetic data generated by the Phase-1 world model — not a real merchant, and not a
        performance claim. See the backtest for the honest result: the engine does not yet beat Stripe Smart Retries
        on recovery rate, which is exactly why the statement bills $0.
      </p>
    </main>
  );
}
